### Create and Update CDA maps for converting to FHIR with RESTClient and running matchbox (locally)
### Note: POST the maps in the following order, if you update one map you need to repost also the maps below

### @host = https://test.ahdis.ch/r4
@host = http://localhost:8080/r4

GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+xml

### 1. POST OrfQrToBundle.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/OrfQrToBundle.map


### 4. POST Questionnaire
POST {{host}}/Questionnaire
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources/Questionnaire-order-referral-form.json


### 2. Transform order-referral-form (QR) to ORF Bundle
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/ch-orf/StructureMap/OrfQrToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources/QuestionnaireResponse-qr-order-referral-form.json

### 2b Using $extract

POST {{host}}/QuestionnaireResponse/$extract
Content-Type: application/fhir+json

< ./fsh-generated/resources/QuestionnaireResponse-qr-order-referral-form.json


### 3. POST OrfBundleToQr.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/OrfBundleToQr.map

### 4. POST OrfBundleToQr.map
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/ch-orf/StructureMap/OrfBundleToQr
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./input/examples/bundle/order-referral-form-mapped.xml

#### Put questionnaire to Brians server
PUT https://sqlonfhir-r4.azurewebsites.net/fhir/Questionnaire/order-referral-form HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./input/examples/questionnaire/order-referral-form.xml

#### Put prepopulation data to Brians server
PUT https://sqlonfhir-r4.azurewebsites.net/fhir/Bundle/order-referral-form HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./input/examples/Bundle/order-referral-form.xml



# see rendering
http://smartqedit4.azurewebsites.net/Questionnaire/Index



#################### further examples ####################

### 2a. Transform order-referral-form to ORF Bundle
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/ch-orf/StructureMap/OrfQrToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources/QuestionnaireResponse-qr-radiology-order.json

### 2b. Transform order-referral-form to ORF Bundle
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/ch-orf/StructureMap/OrfQrToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources/QuestionnaireResponse-qr-xray-report.json

### 2c. Transform order-referral-form to ORF Bundle
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/ch-orf/StructureMap/OrfQrToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources/QuestionnaireResponse-qr-external-diagnostics-order.json

### 2d. Transform order-referral-form to ORF Bundle
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/ch-orf/StructureMap/OrfQrToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources/QuestionnaireResponse-qr-findings-report.json