### Create and Update CDA maps for converting to FHIR with RESTClient and running matchbox (locally)
### Note: POST the maps in the following order, if you update one map you need to repost also the maps below

@host = https://test.ahdis.ch/matchbox/fhir
### @host = http://localhost:8080/matchbox/fhir

GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+xml

### 1. POST OrfQrToBundle.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/OrfQrToBundle.map


### 4. POST Questionnaire
PUT {{host}}/Questionnaire/order-referral-form
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources/Questionnaire-order-referral-form.json


### 2. Transform order-referral-form (QR) to ORF Bundle
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/ch-orf/StructureMap/OrfQrToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources/QuestionnaireResponse-qr-order-referral-form.json

### 2b Using $extract

POST {{host}}/QuestionnaireResponse/$extract
Content-Type: application/fhir+json

< ./fsh-generated/resources/QuestionnaireResponse-qr-order-referral-form.json



### see rendering
http://smartqedit4.azurewebsites.net/Questionnaire/Index



#################### further examples ####################

### 2a. Transform order-referral-form to ORF Bundle
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/ch-orf/StructureMap/OrfQrToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources/QuestionnaireResponse-qr-radiology-order.json

### 2b. Transform order-referral-form to ORF Bundle
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/ch-orf/StructureMap/OrfQrToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./fsh-generated/resources/QuestionnaireResponse-qr-external-diagnostics-order.json


### Error messages
//  This comes from matchbox:
//  FIXME  Error @ StructureMap.group[0].rule[1].rule[0].dependent[0].variable[0].extension[0].url (line 937, col95): URL value 'http://hl7.org/fhir/tools/StructureDefinition/original-item-type' does not resolve
//  However the current validator does not generate an error for this


// use the validator_cli.jar to compile the map
java -jar "/Users/oegger/.vscode/extensions/yannick-lagger.vscode-fhir-tools-1.5.1/validator_cli.jar" -compile http://fhir.ch/ig/ch-orf/StructureMap/OrfQrToBundle -output /Users/oegger/Documents/github/ch-orf/input/resources/structuremap/OrfQrToBundle.xml  -ig /Users/oegger/Documents/github/ch-orf/maps/OrfQrToBundle.map -version 4.0.1
